"""Architecture Decision Records: parsing, creation and index generation.

An ADR is a short Markdown file recording one decision, why it was taken and
what it costs. The format is a lightweight MADR variant:

    # 0003. Use EdDSA for access tokens

    - Status: accepted
    - Date: 2026-09-22
    - Deciders: platform team

    ## Context
    ## Decision
    ## Consequences
    ## Alternatives considered   (optional)
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

FILENAME = re.compile(r"^(\d{4})-([a-z0-9]+(?:-[a-z0-9]+)*)\.md$")
TITLE = re.compile(r"^# (\d{4})\. (.+)$")
META = re.compile(r"^- (Status|Date|Deciders): (.*)$")
SUPERSEDED = re.compile(r"^superseded by \[(\d{4})\]\((\d{4}-[a-z0-9-]+\.md)\)$")

STATUSES = ("proposed", "accepted", "rejected", "deprecated")
REQUIRED_SECTIONS = ("Context", "Decision", "Consequences")
INDEX_FILE = "README.md"
TEMPLATE_FILE = "0000-template.md"


@dataclass
class Adr:
    path: Path
    number: int
    title: str
    status: str
    date: str
    sections: dict[str, str] = field(default_factory=dict)

    @property
    def superseded_by(self) -> str | None:
        match = SUPERSEDED.match(self.status)
        return match.group(2) if match else None


def slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug or "decision"


def parse(path: Path) -> Adr:
    """Parse an ADR file. Missing parts become empty strings; `lint` reports them."""
    lines = path.read_text(encoding="utf-8").splitlines()
    number_match = FILENAME.match(path.name)
    number = int(number_match.group(1)) if number_match else -1
    title, status, day = "", "", ""
    sections: dict[str, list[str]] = {}
    current: list[str] | None = None

    for line in lines:
        if (m := TITLE.match(line)) and not title:
            title = m.group(2).strip()
        elif (m := META.match(line)) and current is None:
            key, value = m.group(1), m.group(2).strip()
            if key == "Status":
                status = value
            elif key == "Date":
                day = value
        elif line.startswith("## "):
            current = sections.setdefault(line[3:].strip(), [])
        elif current is not None:
            current.append(line)

    return Adr(
        path=path,
        number=number,
        title=title,
        status=status,
        date=day,
        sections={name: "\n".join(body).strip() for name, body in sections.items()},
    )


def load_all(directory: Path) -> list[Adr]:
    """Every ADR in `directory`, ordered by number (the template is excluded)."""
    files = [
        p
        for p in directory.glob("*.md")
        if p.name not in (INDEX_FILE, TEMPLATE_FILE) and FILENAME.match(p.name)
    ]
    return sorted((parse(p) for p in files), key=lambda adr: adr.number)


def next_number(directory: Path) -> int:
    return max((adr.number for adr in load_all(directory)), default=0) + 1


def create(directory: Path, title: str, today: date | None = None) -> Path:
    """Write a new `proposed` ADR from the template and return its path."""
    directory.mkdir(parents=True, exist_ok=True)
    number = next_number(directory)
    path = directory / f"{number:04d}-{slugify(title)}.md"
    day = (today or date.today()).isoformat()
    path.write_text(
        f"# {number:04d}. {title}\n\n"
        f"- Status: proposed\n"
        f"- Date: {day}\n"
        f"- Deciders: \n\n"
        "## Context\n\n"
        "What forces are at play? What problem or constraint makes a decision necessary now?\n\n"
        "## Decision\n\n"
        'State the decision in full sentences, in active voice: "We will ...".\n\n'
        "## Consequences\n\n"
        "What becomes easier, what becomes harder, and what do we now have to do?\n\n"
        "## Alternatives considered\n\n"
        "- **Option** — why it was not chosen.\n",
        encoding="utf-8",
    )
    return path


def render_index(directory: Path) -> str:
    """Markdown table of all ADRs, used as `docs/adr/README.md`."""
    rows = [
        f"| [{adr.number:04d}]({adr.path.name}) | {adr.title} | {adr.status} | {adr.date} |"
        for adr in load_all(directory)
    ]
    return (
        "# Architecture Decision Records\n\n"
        "<!-- Generated by `archkit adr index`. Do not edit by hand. -->\n\n"
        "| # | Decision | Status | Date |\n"
        "|---|---|---|---|\n" + "\n".join(rows) + "\n"
    )
